name: Deploy to Firebase on merge
on:
    push:
        branches:
            - main
jobs:
    build_and_deploy:
        if: github.event.repository.full_name == 'thehereward/snapcup'
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: build react app
              run: cd app && npm ci && NODE_ENV=test npm run build
            - name: build functions
              run: cd functions && npm ci && npm run build
            - name: work on default
              uses: w9jds/firebase-action@master
              with:
                  args: use default
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
            - name: deploy firestore rules
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only firestore:rules
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
            - name: deploy app to firebase hosting
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: "${{ secrets.GITHUB_TOKEN }}"
                  firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIR_APP_60892 }}"
                  channelId: live
                  projectId: fir-app-60892
              env:
                  FIREBASE_CLI_PREVIEWS: hostingchannels
            - name: deploy firebase functions
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only functions
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
            - name: Discord notification
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
              uses: Ilshidur/action-discord@master
